### ISSUE TITLE
Update kotlin version

### ISSUE THREAD

**Issue by paurakhsharma** [DimitarPetrov/stegify-flutter-plugin#2]
Hey I have this error due to the older version of kotlin... can you please update the kotlin version
or, suggest me how I can work around this issue?

```
Launching lib/main.dart on RMX1801 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_stegify' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

And thanks for the great plugin :+1:

**Comment by DimitarPetrov** [comment]
@paurakhsharma
Thank you for pointing that out! 👍

I have released new version `0.0.6` can you try with it and verify if the issue persists?

Regards,
Dimitar

**Comment by paurakhsharma** [comment]
Thank you for the quick update.
I will have a look and let you know :slightly_smiling_face:

**Comment by paurakhsharma** [comment]
It works like a charm... Thank you so much.
Closing the issue
